### ISSUE TITLE
Question - `tabbable` mocking in vitest

### ISSUE THREAD

**Issue by dimitur2204** [focus-trap/focus-trap-react#1002]
### Question:

I am having the following error when trying to test components with vitest running js-dom environment.

`Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times`

This is a link to the documentation, where you explain how to fix that issue using mocks with jest https://github.com/focus-trap/tabbable#testing-in-jsdom.

With my previous jest setup I had it running like in that exact way, but am unable to make it work in vitest. 
Maybe it has something to do with vitest not recognizing the `__mocks__` folder? I can't seem to find a way to mock it properly with vitest :/

**Comment by stefcameron** [comment]
@dimitur2204 Good question... I don't know vitest at all so I can't really suggest what to do, but one alternative you could consider to mocking is runtime global variables. This is another feature Jest supports in its [globals option](https://jestjs.io/docs/configuration#globals-object), and it's similar to Webpack's [DefinePlugin](https://webpack.js.org/plugins/define-plugin/) and Rollup's [ReplacePlugin](https://github.com/rollup/plugins/tree/master/packages/replace).

Provided vitest has a similar feature, you would define something like `TEST_ENV: boolean` as a global in vitest, setting it to `true`, and for Webpack/Rollup, you'd set it to `false`.

Then in all your focus traps, you would pass an options object:

```jsx
<FocusTrap
  focusTrapOptions={{
    ...,
    tabbableOptions: {
      displayCheck: TEST_ENV ? 'none' : 'whatever you normally set it to, or undefined for the default'
    }
  }}
>
  <button>I'm trapped</button>
</FocusTrap>
```

**Comment by dimitur2204** [comment]
> Provided vitest has a similar feature, you would define something like `TEST_ENV: boolean` as a global in vitest, setting it to `true`, and for Webpack/Rollup, you'd set it to `false`.
> 
> Then in all your focus traps, you would pass an options object:
> 
> ```js
> <FocusTrap
>   focusTrapOptions={{
>     ...,
>     tabbableOptions: {
>       displayCheck: TEST_ENV ? 'none' : 'whatever you normally set it to, or undefined for the default'
>     }
>   }}
> >
>   <button>I'm trapped</button>
> </FocusTrap>
> ```

After further investigation it turns out that the problem is because of how `tabbable` is bundled. It has no `esm` variant and only uses old style `commonjs`, which `vite` cannot intercept and mock. The `jest.requireActual` that is used, which is now `vi.importActual` does not actually work. The solution you have provided should work though and I will close the issue! Could be reopened in the future, but should probably be in the `tabbable` repo.

**Comment by jordan-rigo** [comment]
Is there a more sophisticated solution for this?

**Comment by tamusil-cen55253** [comment]
This works for me https://github.com/vitest-dev/vitest/discussions/3134#discussioncomment-8863241

**Comment by carloschneider** [comment]
> This works for me [vitest-dev/vitest#3134 (reply in thread)](https://github.com/vitest-dev/vitest/discussions/3134#discussioncomment-8863241)

Thanks!

Here is how I fixed:

```ts
async function mock(mockedUri: string, stub: unknown) {
  const { Module } = (await import('module')) as unknown as {
    Module: Record<string, (uri: string, parent: unknown) => void>
  }

  // eslint-disable-next-line no-underscore-dangle
  Module._load_original = Module._load
  // eslint-disable-next-line no-underscore-dangle
  Module._load = (uri, parent) => {
    if (uri === mockedUri) return stub
    // eslint-disable-next-line no-underscore-dangle
    return Module._load_original(uri, parent)
  }
}

vi.hoisted(async () => {
  const tabbable: typeof Tabbable = await vi.importActual('tabbable')

  return mock('tabbable', {
    ...tabbable,
    tabbable: (node: Element, options: TabbableOptions) =>
      tabbable.tabbable(node, { ...options, displayCheck: 'none' }),
    focusable: (node: Element, options: TabbableOptions) =>
      tabbable.focusable(node, { ...options, displayCheck: 'none' }),
    isFocusable: (node: Element, options: TabbableOptions) =>
      tabbable.isFocusable(node, { ...options, displayCheck: 'none' }),
    isTabbable: (node: Element, options: TabbableOptions) =>
      tabbable.isTabbable(node, { ...options, displayCheck: 'none' }),
  })
})
```

**Comment by rmariuzzo** [comment]
Solved it like this:

```ts
vi.mock(import('focus-trap-react'), async (importOriginal) => {
  const lib = await importOriginal()
  const ProxyComponent = new Proxy(lib.default, {
    construct: (target, [props]: [FocusTrap.Props]) => {
      if (!props.focusTrapOptions) props.focusTrapOptions = {}
      if (!props.focusTrapOptions.tabbableOptions) props.focusTrapOptions.tabbableOptions = {}
      props.focusTrapOptions.tabbableOptions.displayCheck = 'none'
      return new target(props)
    },
  })
  return { ...lib, default: ProxyComponent }
})
```
