### ISSUE TITLE
Files not found on demo website

### ISSUE THREAD

**Issue by StackOverflowIsBetterThanAnyAI** [focus-trap/focus-trap-react#1163]
Hey, I have just found your **demo** website https://focus-trap.github.io/focus-trap-react/demo and I saw that these links are not leading to any github demo source code. They show a _File not found_ error:

animated trigger
https://github.com/focus-trap/focus-trap-react/blob/master/demo/js/animated-trigger.js

demo Iframe with document option applied
https://github.com/focus-trap/focus-trap-react/blob/demoOption/demo/js/demo-iframe.js

Kind regards, Michael

**Comment by stefcameron** [comment]
Oh, thank you so much for taking the time to report this! Looks like a just a couple of typos. I'll get this fixed up soon.

**Comment by stefcameron** [comment]
@StackOverflowIsBetterThanAnyAI Should be fixed in a few minutes once the demo re-deploys. Thanks again!

**Comment by stefcameron** [comment]
@all-contributors add @StackOverflowIsBetterThanAnyAI for demo

**Comment by stefcameron** [comment]
https://github.com/all-contributors add @StackOverflowIsBetterThanAnyAI for example

**Comment by stefcameron** [comment]
@all-contributors add @StackOverflowIsBetterThanAnyAI for example
