### ISSUE TITLE
the demo is broken

### ISSUE THREAD

**Issue by robert-westenberger** [focus-trap/focus-trap-react#1281]
**Description**
The live demo at https://focus-trap.github.io/focus-trap-react/demo/ is broken.
None of the examples are working.

 Probably because https://focus-trap.github.io/focus-trap-react/demo/demo-bundle.js is returning a 404.

**Versions**
N/A

**Sandbox**
N/A
**Screen Capture**
![image](https://github.com/focus-trap/focus-trap-react/assets/44252092/76b6312f-ce34-4d15-a841-6307a14a05d4)

**Comment by stefcameron** [comment]
@robert-westenberger Thank you for alerting me to this! The demo should be fixed now.

**Comment by stefcameron** [comment]
@all-constributors add @robert-westenberger for docs,bug

**Comment by stefcameron** [comment]
@all-contributors add @robert-westenberger for docs,bug
