### ISSUE TITLE
Update to the latest focus-trap to add multiple focus feature

### ISSUE THREAD

**Issue by zioth** [focus-trap/focus-trap-react#180]
The version of `focus-trap` supported by `focus-trap-react` allows you to trap focus to a single element, without exceptions. The latest version of `focus-trap` (released today - 6.2) fixes https://github.com/focus-trap/focus-trap/issues/199 , allowing exceptions. Could you update your `package.json` to support the latest version?

Thanks!

**Comment by zioth** [comment]
Oops. I hadn't realized that the same person owned both repositories. :) I guess this issue can be a pointless reminder then.

**Comment by stefcameron** [comment]
Thanks to @cgood92, this is already happening in #179. It's a bit more complex than just bumping the version. 😄

**Comment by stefcameron** [comment]
And thanks for the follow-up!
