### ISSUE TITLE
Last example on demo website is not working on Firefox

### ISSUE THREAD

**Issue by dannysindra** [focus-trap/focus-trap-react#187]
Steps to reproduce:
1. Open Firefox (I used version 82)
2. Go to http://focus-trap.github.io/focus-trap-react/demo/
3. Open the last example
4. Press tab multiple times, notice that `Another focusable thing` is never get focused

Expected:
`Another focusable thing` should be focus-able

Actual:
This issue found on Firefox 82 (haven't tested on previous versions), but working as expected on Chrome.
There are probably other examples in the demo website which are also not working correctly, I just highlighted the last example.

**Comment by stefcameron** [comment]
@dannysindra Thanks for reporting this! I checked it with Firefox 83 and it seems to be working fine. In case this was related to an old bug in the code 2 years ago (the last time the demo page was updated -- I took over as maintainer only last July and still catching-up), I just updated the demo page with fresh code, as well as 2 new demos, so the one you're referring to here is now the 3rd demo from the end.

Would you be able to check it out again and LMK if there's still an issue?

**Comment by dannysindra** [comment]
Thanks for checking @stefcameron, I just reload the updated demo page again on my Firefox. Unfortunately the issue is still there. Here is my screen recording:

![focus-trap-react](https://user-images.githubusercontent.com/10548708/99892143-b6ab6f80-2c26-11eb-82e6-83b920cb4925.gif)

**Comment by stefcameron** [comment]
Thanks for checking again too, and for the recording. Now that's it's working for me but not for you with the same version of FF, I'll have to play around with it some more. What happens on your side if you do not first click into the auto focused field and instead, just start pressing the tab key?

**Comment by dannysindra** [comment]
No problem, I just tried clicking tab directly after clicking `activate trap`, it is also unable to focus on the link.

**Comment by stefcameron** [comment]
Unfortunately, I can't reproduce this on my system on macOS BigSur 11.0.1 (as well as last release of Catalina) and FireFox 83, so I don't know what the problem might be. Since we're both using FF 83, but it works for me, and not you, I'll have to ask you to investigate the code further. I'm happy to take a PR if you can find the problem and fix it!

**Comment by dannysindra** [comment]
I was checking out other libraries, and found this [explanation](https://github.com/theKashey/react-focus-lock#focusing-in-osx-safarifirefox-is-strange) about firefox/safari quirk on OSX. Closing this as it is not the library's issue.
