### ISSUE TITLE
Use React Testing Library for unit tests

### ISSUE THREAD

**Issue by thawkin3** [focus-trap/focus-trap-react#213]
Hi all,

How would you feel about using Kent Dodds' [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) package to unit test this project? That's probably the most commonly used testing library at this point and is more of an "industry standard" than using the test utils directly like what's currently being done.

I'm happy to submit an MR adding this soon! I just wanted to check if there was some good reason that this is _not_ currently being used.

Thanks!

**Comment by stefcameron** [comment]
Absolutely, YES! That would be awesome. I really like the RTL and it would be great to have unit/integration tests in this package on top of the Cypress e2e tests we have.

**Comment by thawkin3** [comment]
Sweet! I'll put an MR together soon that gets React Testing Library set up.

**Comment by thawkin3** [comment]
Here ya go! https://github.com/focus-trap/focus-trap-react/pull/222
