### ISSUE TITLE
Reverse trap

### ISSUE THREAD

**Issue by eduardodallmann** [focus-trap/focus-trap-react#243]
Hello, how to prevent the elements inside from getting the focus? Allow all elements of the page to receive focus, except for what is inside the component. Basically how to reverse the focus trap?
Like this: https://www.starbucks.com/developer/pattern-library/components/prevent-focus/

**Comment by stefcameron** [comment]
👋 If you disable those elements inside the trap, they should automatically become not-focusable based on what `tabbable` does under the hood: https://github.com/focus-trap/tabbable/blob/c048203822b6b7f59d0b183c06fa229635da68d0/src/index.js#L166

**Comment by eduardodallmann** [comment]
Thanks for the answer. But I am making a Panel component that can be disabled. And regardless of what have inside in children, they should not receive focus.

```
<body>
  elements focused
  <panel disabled>
    whatever children content not focused
  </panel>
  elements focused
</body>
```

**Comment by stefcameron** [comment]
Can you write the Panel component such that when it gets disabled, it also disables all its children?

For example, you would use `tabbable(panel)` to find all the nodes that the trap would allow tabbing to and then set `node.disabled = true` on all of them, as well as perhaps a `.disabled` class or something to remember them all for when the Panel is enabled (then you would select all `.disabled` nodes and set `node.disabled = false`).

But basically, this library doesn't have a "reverse" mode where it excludes certain nodes from being tabbable.

**Comment by stefcameron** [comment]
Something else that might work is to use the [containerElements](https://github.com/focus-trap/focus-trap-react#containerelements) prop and separate the elements you want to have focus from the those you don't into 2 containers. When the Panel is disabled, remove it from the trap's `containerElements`. You should even be able to have 3 containers:
```jsx
<App>
  <Before />
  <Panel />
  <After />
</App>
```
To start, add the refs for Before, Panel, and After to `containerElements`. When Panel is disabled, remove it. Focus should then flow from the last tabbable element in Before to the first one in After, giving the illusion of skipping over whatever is in Panel.

**Comment by stefcameron** [comment]
I feel like there's a reasonable solution without requiring any new features from this library. Closing.
