### ISSUE TITLE
Can you please bump focus-trap to at least 6.6.0 for having escapeDeactivates with the function option?

### ISSUE THREAD

**Issue by c3-tony** [focus-trap/focus-trap-react#415]
Can you please bump focus-trap to at least 6.6.0 for having escapeDeactivates with the function option? thanks 👏 

https://github.com/focus-trap/focus-trap/commit/75be4630bc26395300c517638ffa412606644e6f

**Comment by stefcameron** [comment]
Of course, but it's not just a package.json update. We need to update the typings and prop-types, too, and for the new `initialFocus: false` option as well. I'll try to get to this in the next few days. 🙂

**Comment by stefcameron** [comment]
Look for version 8.7.0 being published right now! 😄
