### ISSUE TITLE
Focus trap should not be forced to 'unpause' when another trap is disabled

### ISSUE THREAD

**Issue by ChavdarSlavov** [focus-trap/focus-trap-react#45]
Found an issue where one trap is incorrectly forced to unpause when another trap is disabled/destroyed.

Here is simple example:

- Preview https://wkj3kk5307.codesandbox.io/
- Code https://codesandbox.io/s/wkj3kk5307

Steps to reproduce:
Click on 'btn 2' to remove second trap.

Result:
Trap 1 (with child 'btn 1') becomes active preventing 'btn 3' from being focused or clicked.

Expectation:
Trap 1 (with child 'btn 1') should remain paused due `<FocusTrap paused={true}>`.
'btn 3' should be focusable and clickable.

**Comment by davidtheclark** [comment]
This is the intentional, as of [v6](https://github.com/davidtheclark/focus-trap-react/blob/master/CHANGELOG.md#600) (see also [focus-trap v4](https://github.com/davidtheclark/focus-trap/blob/master/CHANGELOG.md#400)).

**Comment by ChavdarSlavov** [comment]
Ok i understand, the reasoning behind the unpausing, but in this case the two traps are not related at all,  trap 1 was not paused because trap 2 was started, so it make no sense to be unpaused when trap 2 is removed.
Also shouldn't  `paused` attribute be checked before unpausing to make sure the trap is legitimate candidate for unpausing. In my example `paused={true}` is disregarded.

**Comment by davidtheclark** [comment]
Ok: fix welcome.

**Comment by stefcameron** [comment]
Closing very old issues. There have been a lot of improvements to the library (and tabbable and focus-trap) since I took over in July 2020, and this may be fixed now. If it's still an issue with the current release, feel free to re-open.

Note that since, we've added support for multiple containers in a single trap. Maybe that helps?
