### ISSUE TITLE
Can't focus iframes in FocusTrap

### ISSUE THREAD

**Issue by MaxDagerbratt** [focus-trap/focus-trap-react#459]
We're having problems with focusing iframes within a <FocusTrap>

Here's an example where you can't focus the YouTube iframe until it has been manually pressed with the mouse.
https://codesandbox.io/s/xenodochial-scott-77h3h?file=/src/App.js

This problem persists with other YouTube playback packages as well, such as: https://www.npmjs.com/package/react-youtube

**Comment by dziul** [comment]
As I understand it, you need in this case to use [refs](https://en.reactjs.org/docs/refs-and-the-dom.html) with the `focusTrapOptions.initialFocus` prop of `FocusTrap`. See if the lib you are using has the iframe ref available. Also, you need to [indicate that the iframe can receive focus](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex), adding `tabindex=-1`, for example.

From what I saw quickly, this lib you are using doesn't return the element's ref, I would need to make an alternative.


_I'm just a user_ 😁

**Comment by stefcameron** [comment]
Refs might help, but there's also the fact that there is no focusable element following the iframe, only before, which seems to be a requirement, for some reason (I'm the maintainer, but inherited these libs long after that was a thing, so I admit I'm not certain why it is the way it is). The `iframe` [focus-trap demo](https://codesandbox.io/s/suspicious-shadow-w9vou) mentions the need for a focusable element before and after, [which seems to work](https://codesandbox.io/s/suspicious-shadow-w9vou).

**Comment by stefcameron** [comment]
FYI, I just published focus-trap 6.7.0 which fixed an issue with iframes when you have a focus trap inside an iframe. Probably not quite this use case, though. Just FYI.

I'm going to close this since iframes are working according to what's been documented (see my previous comment). If you have an idea how to improve it, please feel free to open a PR.
