### ISSUE TITLE
Get rid of deprecated React.findDOMNode

### ISSUE THREAD

**Issue by RichardJuchelka** [focus-trap/focus-trap-react#47]
React.StrictMode throws an error as focus-trap-react uses deprecated React API. See https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage

Could you please update the package to work with RefObject?

**Comment by davidtheclark** [comment]
For now I'd rather continue supporting React 15 than support strict mode. Is it possible to do both?

**Comment by stefcameron** [comment]
Closing in favor of #77.
