### ISSUE TITLE
How to trap focus in the iframe?

### ISSUE THREAD

**Issue by xnslx** [focus-trap/focus-trap-react#642]
Hey, here is the [codesandbox](https://codesandbox.io/s/jolly-haibt-egjw39), I am trying to combine image and video together in the embla carousel, when the slide is a video, the focus is losing, and no way to use the trackpad to slide up and down. I have a hard time wrapping my head around this question. Many thanks!

**Comment by stefcameron** [comment]
Hello, @xnslx !

Thanks for the sandbox, but it looks like it isn't using focus-trap-react. It's being imported, but not used.

I'm not familiar with this "Embla Carousel".

At what point does the focus get lost? Maybe you add a FocusTrap how you think you'd use it, and then take a video (animated GIF or something) of the problems you're seeing so we can try to see what's going on? Also, explaining what you're expecting to happen would help.

**Comment by stefcameron** [comment]
Closing. If it's still an issue, feel free to re-open.
