### ISSUE TITLE
Problems resetting trigger element focus for always-rendered elements

### ISSUE THREAD

**Issue by Smolations** [focus-trap/focus-trap-react#69]
Heeeeeey, first off, thanks for creating this standalone component! It's been useful for me in creating some modal dialog components.

Unfortunately, my component's original transitions get broken when I wrap the dialog with the `FocusTrap`. I use a ref to pass to another component which provides callbacks when transitions start/end, but it seems that this component overrides that ref with another instead of looking for one that is existing.

This is the conditional for the render:
```js
      {ariaModal && open
        ? (<FocusTrap focusTrapOptions={focusTrapOptions}>{renderDialog()}</FocusTrap>)
        : renderDialog()
      }
```

This is the behavior _without_ the focus trap:
![modal_dialog_no_focus_trap](https://user-images.githubusercontent.com/952681/78611498-5ba64300-7824-11ea-84b6-902511d291b1.gif)

And this is the behavior _with_ the focus trap:
![modal_dialog_with_focus_trap](https://user-images.githubusercontent.com/952681/78611522-69f45f00-7824-11ea-91f1-5d37e88fc982.gif)

It would seem to me that it might be trivial to update code that attaches the ref to look for an existing ref, but I've never done that before so it's hard to say. If there is any workaround or anything, I'd love to know! It's also possible that something else is going on as I don't understand why the transitions themselves are broken given that they are specified 100% in the css and only their events are tracked based on the ref. Any insight here is welcome!

**EDIT:** (renamed issue after discovering root issue) Now that I'm thinking about it, the different conditional renders might be causing the css transform transitions to fail since there is new parent markup. That markup probably causes a brand new render on the dialog whose initial state is open and therefore transitions from nowhere. The only reason I did it that way is that _always_ rendering the focus trap means that the initial mount is the only time the trap grabs the trigger element (so it can be refocused on dialog close). I originally tried to get around this by using state to grab the `document.activeElement` when the dialog is set to open and then passing that to the trap component via a `setReturnFocus` function, but it didn't seem to get honored on subsequent re-renders when toggling the trap's `active` state.

It would seem this library doesn't take into account **elements which always exist in a view** and are either hidden via display/visibility properties or via positioning properties that shove elements off screen until their "open" state is triggered. Please help!  😓

**Comment by Smolations** [comment]
Did a bit more digging on this, and found the code related to deactivation of the trap:
```js
  componentDidUpdate(prevProps) {
    if (prevProps.active && !this.props.active) {
      const { returnFocusOnDeactivate } = this.props.focusTrapOptions;
      const returnFocus = returnFocusOnDeactivate || false;
      const config = { returnFocus };
      this.focusTrap.deactivate(config);
```

Looks like you only pull `returnFocusOnDeactivate` from the trap options and then create a config to pass to the focus trap with only that boolean value. The `focus-trap` docs say that `onDeactivate` is also supported, but it is not being passed. I'm guessing trying to do my own refocusing on the trigger element there might conflict with the existing logic, so perhaps that isn't the best solution. Ideally, passing `setReturnFocus` as a function to `deactivate` would work out, but looks like my use case isn't supported out of the box. 

Would it be accurate to say that this component (and maybe the underlying library) only support trap-on-mount scenarios and disallow resetting any of the initial settings?

**Comment by stefcameron** [comment]
Closing very old issues. There have been a lot of improvements to the library (and tabbable and focus-trap) since I took over in July 2020, and this may be fixed now. If it's still an issue with the current release, feel free to re-open.
