### ISSUE TITLE
Version 9.0.1 crashes previously working code

### ISSUE THREAD

**Issue by Slapbox** [focus-trap/focus-trap-react#719]
I assume 9.0.0 would do the same. The error we get is `el.querySelectorAll is not a function`, but I'm not really sure of the cause beyond that.

**Comment by stefcameron** [comment]
Hmm, the only change in 9.0.1 is a package dependency change. If you could dig deeper on your end and provide more specifics, that would help a lot...

**Comment by Slapbox** [comment]
The issue affects `9.0.0` also. It fails on this line in Tabbable:

`var candidates = Array.prototype.slice.apply(el.querySelectorAll(candidateSelector));`

This appears to be because we use `react-onclickoutside` inside of the `<FocusTrap />`. I'll see if a simple refactor on our end can fix this.

The underlying issue is that to access the actual component node the code would need to access `el.componentNode` - see below:

![image](https://user-images.githubusercontent.com/6835891/173939828-ea6b3540-0313-4584-83b9-9f855848e0c5.png)

Thanks again for your great work on this library!

**Comment by stefcameron** [comment]
Interesting! Thanks for digging into it. I'm surprised this only surfaced as of 9.0.0, unless the use of `ReactDOM.findDOMNode(what-react-onclickoutside-gives-you)` was somehow masking this issue. Actually, I guess it may have been finding that component node for you, and now without the use of this API, you need to correctly pass it in.

> Thanks again for your great work on this library!

My pleasure! 😄

**Comment by stefcameron** [comment]
🎉
