### ISSUE TITLE
IE11 Error: Object doesn't support property or method 'contains'.

### ISSUE THREAD

**Issue by jamesjbergeron** [focus-trap/focus-trap-react#746]
After updating focus-trap-react to latest version (9.0.2) I am experiencing issues using the focus trap in IE11 browser.

The error shown is: Object doesn't support property or method 'contains'.

![image](https://user-images.githubusercontent.com/39500084/179602447-3cec115f-639e-4de9-bf4b-7d2b3ac62613.png)

Note: I seem to encounter this error with underlying tababble versions starting with 5.3.2. However, with version 5.3.1 I do not encounter this error.

**Comment by stefcameron** [comment]
Thanks for using focus-trap-react, and also for digging a bit and giving an error message.

Based on that, I would assume it was [this spot](https://github.com/focus-trap/tabbable/commit/aa2a699d7e9d37628a7b1208ba700eb85b42a31e#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R283) in the main code change in Tabbable v5.3.2: The additional of 2 statements that expect `.contains()` to exist on the owner document.

Unfortunately, it looks like the `Node.contains()` API is only supported on `HTMLElement` nodes, not the `document`, in IE9-11: https://caniuse.com/mdn-api_node_contains

And also unfortunately, IE11 was [officially retired](https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/) on June 15, 2022 (last month).

I actually have a task to update tabbable, focus-trap, and focus-trap-react READMEs to state that they no longer support Internet Explorer altogether -- granted tabbable v5.3.2 was published on May 6, 2022. My bad on breaking IE11 back then, but there is basically no incentive to fix this issue anymore.

I'm going to close the issue, but happy to keep conversing on it.
