### ISSUE TITLE
Unknown Your focus-trap must have at least one container with at least one tabbable node in it at all times error

### ISSUE THREAD

**Issue by JayBox325** [focus-trap/focus-trap-react#785]
I am using this focus-trap library for my menu, but I am getting the `Your focus-trap must have at least one container with at least one tabbable node in it at all times` and I can't see why when I have a single child container and many links within.

```
<FocusTrap active={menuIsOpen}>
                    <div className="xl:grid xl:grid-cols-24" id="menu">

                        <nav className="xl:col-start-2 xl:col-span-22">
                            <ul className="title-5 text-left space-y-4">
                                {menuItems?.map((item, n) => (
                                    <li key={n}>
                                        <Link href={`/${item.nodeUri}`}><a className="hover:text-blue transition-colors">{item.title}</a></Link>
                                    </li>
                                ))}
                            </ul>
                            <div className="mt-6">
                                <SocialAccounts socialAccounts={socialAccounts} />
                            </div>
                        </nav>

                        <button className="absolute -transform-x-1/2 flex items-center justify-center bg-deep-600 bg-opacity-30 top-6 right-6 xl:top-12 xl:right-12 hover:bg-opacity-100 transition-colors rounded-md w-12 h-12 md:h-14 md:w-14 xl:w-16 xl:h-16" onClick={()=>{setMenuIsOpen(false)}}>
                            <span className="sr-only">Close menu</span>
                            <XMarkIcon className="h-6 w-6 md:w-8 md:h-8 xl:w-12 xl:h-12" />
                        </button>

                    </div>
                </FocusTrap>
```

**Comment by 000dry** [comment]
Have you seen this? https://github.com/focus-trap/tabbable#testing-in-jsdom

I'm a bit lost to what value tabbable actually adds in this context. It seems like FocusTrap is trying to assert that the child container has a valid tabbable element.

In my opinion, it would be better to let users of FocusTrap make their own mistakes and not cause such a disruption to tests.

**Comment by stefcameron** [comment]
Are we talking about a test env or a browser env? That's not clear so far.

In any case, that exception is throw by focus-trap when it has nothing to set focus to inside the container(s) which it has been given to trap focus within. That seems like an error state to me.

This particular error frequently arises from indirectly using focus-trap in the context of focus-trap-react, and it's usually related to when things are rendered by React and when nodes are available.

focus-trap-react does try its best to work with a trap that has no containers in which to trap focus. It attempts to delay the creation and activation of the underlying strap until it sees it has a container element in which to trap focus.

A repro would probably be best here to see why the trap is failing like this, since it does _seem_ like there should be some focusable and tabbable nodes in there (i.e. a button and maybe some anchors).

There's a couple of examples here https://github.com/focus-trap/focus-trap-react#usage also a bit further down that might help.

**Comment by JayBox325** [comment]
I have identified the issue with my menu.

My menu wrapper has visibility being set when it's hidden & shown, and without this it works perfectly...

```
<div className={`fixed z-60 top-0 transition-all duration-500 left-0 right-0 bottom-0 flex-col justify-center flex ${menuIsOpen ? 'opacity-100 visible delay-[300ms]' : 'opacity-0 invisible delay-[0ms]'}`}>
            <FocusTrap
                active={menuIsOpen}
            >
                <div className="container">
                    <div className="xl:grid xl:grid-cols-24" id="menu">

                        <nav className="xl:col-start-2 xl:col-span-22">
                            <ul className="title-5 text-left space-y-4">
                                {menuItems?.map((item, n) => (
                                    <li key={n}>
                                        <Link href={`/${item.nodeUri}`}><a className="hover:text-blue transition-colors">{item.title}</a></Link>
                                    </li>
                                ))}
                            </ul>
                            <div className="mt-6">
                                <SocialAccounts socialAccounts={socialAccounts} />
                            </div>
                        </nav>

                        <button className="absolute -transform-x-1/2 flex items-center justify-center bg-deep-600 bg-opacity-30 top-6 right-6 xl:top-12 xl:right-12 hover:bg-opacity-100 transition-colors rounded-md w-12 h-12 md:h-14 md:w-14 xl:w-16 xl:h-16" onClick={()=>{setMenuIsOpen(false)}}>
                            <span className="sr-only">Close menu</span>
                            <XMarkIcon className="h-6 w-6 md:w-8 md:h-8 xl:w-12 xl:h-12" />
                        </button>

                    </div>
                </div>
            </FocusTrap>
        </div>
```

However, the issue with this is that users are still able to tab into it when it's hidden without it being set to invisible.

**Comment by stefcameron** [comment]
This is starting to point to the [breaking change](https://github.com/focus-trap/focus-trap-react/blob/master/CHANGELOG.md#1000) in v10.0.0 all the way down in Tabbable (through focus-trap to tabbable). Is the issue resolved when you use the [legacy-full](https://github.com/focus-trap/focus-trap-react/blob/af69c14710e04f46648f9faca1b3e815e4f567f5/src/focus-trap-react.js#L458) `displayCheck` mode on your trap?

**Comment by JayBox325** [comment]
Thanks for getting back to me @stefcameron. However, I have updated my above code to include:

```
<FocusTrap
                active={menuIsOpen}
                focusTrapOptions={{
                    tabbableOptions: {
                        displayCheck: 'legacy-full'
                    }
                }}
            >
```

And the same thing is happening.

**Comment by stefcameron** [comment]
@JayBox325 My pleasure, and thanks for giving that a try.

In that case, I also noticed that in this condition to showing/hiding the menu, `menuIsOpen ? 'opacity-100 visible delay-[300ms]' : 'opacity-0 invisible delay-[0ms]'`, there is a delay of 300ms when opening the menu.

The delay in showing the menu which contains the trap cause issues that could result in the exception you're experiencing, which is [thrown](https://github.com/focus-trap/focus-trap/blob/master/index.js#L331) by focus-trap's `updateTabbableNodes()` function when it doesn't find anything tabbable.

In this situation, focus-trap has the `checkCanFocusTrap()` option, which you might be able to use to work around this in your use case. As you can [see](https://github.com/focus-trap/focus-trap/blob/master/index.js#L674-L680), using that option causes the focus-trap to delay calling `upgradeTabbableNodes()` until the returned promise has settled.

The [animated dialog](https://focus-trap.github.io/focus-trap/#demo-animated-dialog) demo demonstrates the use of this option. The demo actually looks like it might be similar to your slowly appearing menu...

**Comment by JayBox325** [comment]
Hi @stefcameron, thanks again!

I did think about the delay, and tried taking that off, but still no dice. However, I have handled this in another way thanks to your post about when the nodes are visible to tabbable.

I have got two states:

* `menuIsOpen` for when the menu has been toggled open
* `menuIsVisible` for when the menu has been toggled and gets set after a 50ms timeout after `menuIsOpen` is set to true!

So I am now just using `menuIsVisible` to toggle the keyboard trapping. Brilliant, thanks!

**Comment by stefcameron** [comment]
@JayBox325 Wonderful! Glad I could help. I'm going to close this issue now since it sounds like you have a solution. All the best!

**Comment by JayBox325** [comment]
Thanks, yeah, this is all resolved. Appreciate your help.

**Comment by antonijak** [comment]
hm setting a timeout seems like a hacky solution to me, is there a way to actually solve this?
