### ISSUE TITLE
Add option to retain ability to click with mouse on outside elements

### ISSUE THREAD

**Issue by JayBox325** [focus-trap/focus-trap-react#888]
I have a cart and menu drawers that both share a mask element that is clickable to close whichever one is open when it's clicked, but I have realised that anything outside of the focus state is no longer clickable once the focus-trap is active.

How can I not disable mouse interactivity when the trap is on?

I'm looking to optimise the keyboard-only user experience, but not hinder the mouse one.

Thanks!

**Comment by stefcameron** [comment]
@JayBox325 Sounds like a case for the `allowOutsideClick` focus-trap [option](https://github.com/focus-trap/focus-trap#createoptions)?

**Comment by JayBox325** [comment]
Yep. Thanks. It's been a long pre-christmas day! Thanks!

**Comment by stefcameron** [comment]
My pleasure. Merry Christmas! 🎄
