### ISSUE TITLE
Error: Uncaught [SyntaxError: 'slot):not([inert]' is not a valid selector]

### ISSUE THREAD

**Issue by cwellmoney20** [focus-trap/focus-trap-react#992]
This is my first time using this library, so maybe I'm doing something wrong. But when I run my tests I am seeing this error: 
`Error: Uncaught [SyntaxError: 'slot):not([inert]' is not a valid selector]`

Have you seen this before? I did some digging and the error may thrown from focus-trap/tabbable 

We're using @testing-library/react and @testing-library/jest-dom

Here is an example of some of the code:
```
             <FocusTrap
                focusTrapOptions={{
                  clickOutsideDeactivates: true,
                  fallbackFocus: '#dialog-content-container',
                }}
              >
                <div id="dialog-content-container" tabIndex={-1}>
                  <div className="y_modal-content">{children}</div>
                </div>
              </FocusTrap>
```

**Comment by stefcameron** [comment]
Yes, please see #986. It's a dependency issue. Fixed just today in v10.1.2 🙂
